<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\ContentStatus;
use App\Enums\OgType;
use App\Models\BlogPost;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\BlogPost>
 */
class BlogPostFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<\App\Models\BlogPost>
     */
    protected $model = BlogPost::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->sentence(6),
            // slug is auto-generated by HasSlug trait
            'status' => ContentStatus::Draft,
            'content_blocks' => null,
            'meta_title' => null,
            'meta_description' => null,
            'meta_author' => null,
            'meta_robots' => false,
            'canonical_url' => null,
            'og_title' => null,
            'og_description' => null,
            'og_type' => OgType::Article,
            'og_image' => null,
            'twitter_title' => null,
            'twitter_description' => null,
            'twitter_image' => null,
            'breadcrumbs' => null,
        ];
    }

    /**
     * Indicate that the blog post should be published.
     */
    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::Published,
        ]);
    }

    /**
     * Indicate that the blog post should be a draft (explicit state).
     */
    public function draft(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::Draft,
        ]);
    }

    /**
     * Add sample content blocks (article hero and conclusion CTA).
     */
    public function withContentBlocks(): static
    {
        return $this->state(fn (array $attributes) => [
            'content_blocks' => [
                [
                    'type' => 'hero',
                    'data' => [
                        'heading' => fake()->sentence(8),
                        'lede' => fake()->paragraph(3),
                        'image' => fake()->imageUrl(1920, 1080, 'article', true),
                        'cta_button_text' => 'Read More',
                    ],
                ],
                [
                    'type' => 'cta',
                    'data' => [
                        'heading' => 'Ready to learn more?',
                        'lede' => fake()->paragraph(2),
                        'cta_button_text' => 'Subscribe to Newsletter',
                    ],
                ],
            ],
        ]);
    }

    /**
     * Fill all SEO fields with sample data for blog articles.
     */
    public function withSeoData(): static
    {
        $title = fake()->sentence(8);
        $description = fake()->paragraph(2);
        $image = fake()->imageUrl(1200, 630, 'article', true);
        $author = fake()->name();

        return $this->state(fn (array $attributes) => [
            'meta_title' => $title,
            'meta_description' => $description,
            'meta_author' => $author,
            'meta_robots' => true,
            'canonical_url' => fake()->url(),
            'og_title' => $title,
            'og_description' => $description,
            'og_type' => OgType::Article,
            'og_image' => $image,
            'twitter_title' => $title,
            'twitter_description' => $description,
            'twitter_image' => $image,
            'breadcrumbs' => [
                ['label' => 'Home', 'url' => '/'],
                ['label' => 'Blog', 'url' => '/blog'],
                ['label' => fake()->words(3, true), 'url' => null],
            ],
        ]);
    }
}
