<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\ContentStatus;
use App\Enums\OgType;
use App\Models\Page;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Page>
 */
class PageFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<\App\Models\Page>
     */
    protected $model = Page::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->words(3, true),
            // slug is auto-generated by HasSlug trait
            'template' => 'default',
            'status' => ContentStatus::Draft,
            'content_blocks' => null,
            'meta_title' => null,
            'meta_description' => null,
            'meta_author' => null,
            'meta_robots' => false,
            'canonical_url' => null,
            'og_title' => null,
            'og_description' => null,
            'og_type' => OgType::Website,
            'og_image' => null,
            'twitter_title' => null,
            'twitter_description' => null,
            'twitter_image' => null,
            'breadcrumbs' => null,
        ];
    }

    /**
     * Indicate that the page should be published.
     */
    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::Published,
        ]);
    }

    /**
     * Indicate that the page should be a draft (explicit state).
     */
    public function draft(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::Draft,
        ]);
    }

    /**
     * Add sample content blocks (hero and CTA).
     */
    public function withContentBlocks(): static
    {
        return $this->state(fn (array $attributes) => [
            'content_blocks' => [
                [
                    'type' => 'hero',
                    'data' => [
                        'heading' => fake()->sentence(6),
                        'lede' => fake()->paragraph(2),
                        'image' => fake()->imageUrl(1920, 1080, 'business', true),
                        'cta_button_text' => fake()->words(2, true),
                    ],
                ],
                [
                    'type' => 'cta',
                    'data' => [
                        'heading' => fake()->sentence(4),
                        'lede' => fake()->paragraph(1),
                        'cta_button_text' => fake()->words(3, true),
                    ],
                ],
            ],
        ]);
    }

    /**
     * Fill all SEO fields with sample data.
     */
    public function withSeoData(): static
    {
        $title = fake()->sentence(6);
        $description = fake()->paragraph(1);
        $image = fake()->imageUrl(1200, 630, 'business', true);

        return $this->state(fn (array $attributes) => [
            'meta_title' => $title,
            'meta_description' => $description,
            'meta_author' => fake()->name(),
            'meta_robots' => true,
            'canonical_url' => fake()->url(),
            'og_title' => $title,
            'og_description' => $description,
            'og_type' => OgType::Website,
            'og_image' => $image,
            'twitter_title' => $title,
            'twitter_description' => $description,
            'twitter_image' => $image,
            'breadcrumbs' => [
                ['label' => 'Home', 'url' => '/'],
                ['label' => fake()->word(), 'url' => null],
            ],
        ]);
    }

    /**
     * Set a specific template for the page.
     */
    public function withTemplate(string $template): static
    {
        return $this->state(fn (array $attributes) => [
            'template' => $template,
        ]);
    }
}
