<?php

declare(strict_types=1);

namespace Database\Factories;

use App\Enums\ContentStatus;
use App\Enums\OgType;
use App\Models\Service;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Service>
 */
class ServiceFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<\App\Models\Service>
     */
    protected $model = Service::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'name' => fake()->words(3, true),
            // slug is auto-generated by HasSlug trait
            'status' => ContentStatus::Draft,
            'content_blocks' => null,
            'meta_title' => null,
            'meta_description' => null,
            'meta_author' => null,
            'meta_robots' => false,
            'canonical_url' => null,
            'og_title' => null,
            'og_description' => null,
            'og_type' => OgType::Website,
            'og_image' => null,
            'twitter_title' => null,
            'twitter_description' => null,
            'twitter_image' => null,
            'breadcrumbs' => null,
        ];
    }

    /**
     * Indicate that the service should be published.
     */
    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::Published,
        ]);
    }

    /**
     * Indicate that the service should be a draft (explicit state).
     */
    public function draft(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => ContentStatus::Draft,
        ]);
    }

    /**
     * Add sample content blocks (hero and CTA) with service-specific content.
     */
    public function withContentBlocks(): static
    {
        return $this->state(fn (array $attributes) => [
            'content_blocks' => [
                [
                    'type' => 'hero',
                    'data' => [
                        'heading' => fake()->randomElement([
                            'Professional Web Development Services',
                            'Expert Digital Marketing Solutions',
                            'Custom Software Development',
                            'Strategic Business Consulting',
                            'Technical SEO & Analytics Services',
                        ]),
                        'lede' => fake()->randomElement([
                            'Transform your business with our proven consulting methodology. We deliver results that drive growth and exceed expectations.',
                            'Partner with our expert team to achieve your business goals. Comprehensive solutions tailored to your unique needs.',
                            'Unlock your potential with strategic guidance from industry professionals. Innovation meets excellence in every project.',
                        ]),
                        'image' => fake()->imageUrl(1920, 1080, 'business', true),
                        'cta_button_text' => fake()->randomElement([
                            'Get Started',
                            'Request Consultation',
                            'Learn More',
                        ]),
                    ],
                ],
                [
                    'type' => 'cta',
                    'data' => [
                        'heading' => fake()->randomElement([
                            'Ready to Transform Your Business?',
                            'Let\'s Build Something Amazing Together',
                            'Start Your Journey Today',
                        ]),
                        'lede' => fake()->randomElement([
                            'Contact us for a free consultation and discover how our services can accelerate your success.',
                            'Schedule a call with our experts to discuss your project requirements and goals.',
                        ]),
                        'cta_button_text' => fake()->randomElement([
                            'Schedule Consultation',
                            'Contact Our Team',
                            'Get a Quote',
                        ]),
                    ],
                ],
            ],
        ]);
    }

    /**
     * Fill all SEO fields with service-specific sample data.
     */
    public function withSeoData(): static
    {
        $serviceType = fake()->randomElement([
            'Web Development',
            'Digital Marketing',
            'Business Consulting',
            'Software Development',
            'Technical SEO',
        ]);

        $title = $serviceType.' Services | '.fake()->company();
        $description = 'Professional '.strtolower($serviceType).' services tailored to your business needs. '.fake()->sentence(8);
        $image = fake()->imageUrl(1200, 630, 'business', true);

        return $this->state(fn (array $attributes) => [
            'meta_title' => $title,
            'meta_description' => $description,
            'meta_author' => fake()->name(),
            'meta_robots' => true,
            'canonical_url' => fake()->url().'/services/'.fake()->slug(3),
            'og_title' => $title,
            'og_description' => $description,
            'og_type' => OgType::Website,
            'og_image' => $image,
            'twitter_title' => $title,
            'twitter_description' => $description,
            'twitter_image' => $image,
            'breadcrumbs' => [
                ['label' => 'Home', 'url' => '/'],
                ['label' => 'Services', 'url' => '/services'],
                ['label' => $serviceType, 'url' => null],
            ],
        ]);
    }
}
